export const SUPPORTED_LANGUAGE_SLUGS = [
  "cpp",
  "java",
  "python3",
  "python",
  "javascript",
  "typescript",
  "csharp",
  "c",
  "golang",
  "kotlin",
  "swift",
  "rust",
  "ruby",
  "php",
  "dart",
  "scala",
  "elixir",
  "erlang",
  "racket",
  "mysql",
  "mssql",
  "postgresql",
  "oraclesql",
  "pythondata",
  "bash",
] as const

export type SupportedLanguage = (typeof SUPPORTED_LANGUAGE_SLUGS)[number]

export const LANGUAGE_LABELS: Record<SupportedLanguage, string> = {
  cpp: "C++",
  java: "Java",
  python3: "Python3",
  python: "Python",
  javascript: "JavaScript",
  typescript: "TypeScript",
  csharp: "C#",
  c: "C",
  golang: "Go",
  kotlin: "Kotlin",
  swift: "Swift",
  rust: "Rust",
  ruby: "Ruby",
  php: "PHP",
  dart: "Dart",
  scala: "Scala",
  elixir: "Elixir",
  erlang: "Erlang",
  racket: "Racket",
  mysql: "MySQL",
  mssql: "MS SQL Server",
  postgresql: "PostgreSQL",
  oraclesql: "Oracle",
  pythondata: "Pandas",
  bash: "Bash",
}

export const LANGUAGE_EXTENSIONS: Record<SupportedLanguage, string> = {
  cpp: "cpp",
  java: "java",
  python3: "py",
  python: "py",
  javascript: "js",
  typescript: "ts",
  csharp: "cs",
  c: "c",
  golang: "go",
  kotlin: "kt",
  swift: "swift",
  rust: "rs",
  ruby: "rb",
  php: "php",
  dart: "dart",
  scala: "scala",
  elixir: "exs",
  erlang: "erl",
  racket: "rkt",
  mysql: "sql",
  mssql: "sql",
  postgresql: "sql",
  oraclesql: "sql",
  pythondata: "py",
  bash: "sh",
}

export const LINE_COMMENTS: Record<SupportedLanguage, string> = {
  cpp: "//",
  java: "//",
  python3: "#",
  python: "#",
  javascript: "//",
  typescript: "//",
  csharp: "//",
  c: "//",
  golang: "//",
  kotlin: "//",
  swift: "//",
  rust: "//",
  ruby: "#",
  php: "#",
  dart: "//",
  scala: "//",
  elixir: "#",
  erlang: "%",
  racket: ";",
  mysql: "--",
  mssql: "--",
  postgresql: "--",
  oraclesql: "--",
  pythondata: "#",
  bash: "#",
}
